### PR TITLE
Windows seperator fix

### PR DESCRIPTION
**Pull request by sebald**
Super small fix: use `path.sep` instead of hardcoded `/`

PS: Thanks for the plugin!!! :-)

### CODE REVIEW

**Comment by luckydrq** [comment]
Great, thank you! But it seems ci failed, could you please fix the test cases?

**Comment by sebald** [comment]
Of course, but I am not sure why the CI failed. To me it seems like the build failed because there is no Travis config (`Could not find .travis.yml, using standard configuration.`) and the default configuration required a `rake` file to be present.

If I am wrong, can you point me to the error?

**Comment by luckydrq** [comment]
uh, my bad, sorry!

**Comment by luckydrq** [comment]
:100:

**Comment by luckydrq** [comment]
node-path-extras@0.4.1

**Comment by luckydrq** [comment]
travis ci added

**Pull request merged**
